### ISSUE TITLE
Could't get the ListInput to render

### ISSUE THREAD

**Issue by anselmelly** [konstaui/konsta#48]
```text
<svelte:element this="input"> is self-closing and cannot have content.
Error: <svelte:element this="input"> is self-closing and cannot have content.
    at Proxy.validate_void_dynamic_element (/home/ansel/Development/svelte/kudura-app/node_modules/svelte/internal/index.js:2082:15)
    at eval (/node_modules/konsta/svelte/components/ListInput.svelte:243:31)
    at eval (/node_modules/konsta/svelte/components/ListInput.svelte:245:10)
    at Object.inner (ListInput.svelte:198:16)
    at eval (/node_modules/konsta/svelte/components/ListItem.svelte:268:33)
    at eval (/node_modules/konsta/svelte/components/ListItem.svelte:270:13)
    at ListItem.svelte:163:14
    at eval (/node_modules/konsta/svelte/components/ListItem.svelte:318:8)
    at ListItem.svelte:156:10
    at Object.$$render (/home/ansel/Development/svelte/kudura-app/node_modules/svelte/internal/index.js:1758:22)
```

**Comment by anselmelly** [comment]
https://stackblitz.com/edit/sveltejs-kit-template-default-3x26je?file=src/routes/index.svelte

**Comment by anselmelly** [comment]
🙏🏽  Thank you
