### ISSUE TITLE
ES6 imports "module"

### ISSUE THREAD

**Issue by pi0neerpat** [konstaui/konsta#56]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/pi0neerpat/redwood-capacitor-konsta-demo/tree/prerender-konsta-module-issue

### Bug description

This is the beginning of hopefully a longer marriage of mobile support to the RedwoodJS framework (https://redwoodjs.com) via tools like Konsta, Capacitor, and Framework7. I created a demo which I have successfully running on Android https://github.com/pi0neerpat/redwood-capacitor-konsta-demo/tree/prerender-konsta-module-issue

 Everything works smoothly until adding prerender (server side rendering https://redwoodjs.com/docs/prerender#prerendering-a-page)

> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dev/repos/redwood-capacitor-konsta-demo/node_modules/konsta/react/cjs/konsta-react.js from /home/dev/repos/redwood-capacitor-konsta-demo/web/src/App.tsx not supported.
konsta-react.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename konsta-react.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/dev/repos/redwood-capacitor-konsta-demo/node_modules/konsta/react/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.newLoader [as .js] (/home/dev/repos/redwood-capacitor-konsta-demo/node_modules/pirates/lib/index.js:141:7)
    at Object.<anonymous> (/home/dev/repos/redwood-capacitor-konsta-demo/web/src/App.tsx:12:15)
    at Module._compile (/home/dev/repos/redwood-capacitor-konsta-demo/node_modules/pirates/lib/index.js:136:24)
    at Object.newLoader [as .tsx] (/home/dev/repos/redwood-capacitor-konsta-demo/node_modules/pirates/lib/index.js:141:7)
    at /home/dev/repos/redwood-capacitor-konsta-demo/node_modules/@redwoodjs/prerender/dist/runPrerender.js:52:126

Neither option works

```js
import { KonstaProvider } from 'konsta/react'
// const { KonstaProvider } = require('konsta/react')
```

The only fix I found was to manually remove `"type": "module"` from both `konsta/shared/package.json` and `konsta/react/package.json`

### Konsta UI version

0.10.2

### Platform/Target and Browser Versions

Ubuntu 20

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by shermanlai** [comment]
+1 This would be extremely helpful as it can be loaded with remixjs and others. Not sure if it will break other tools.

**Comment by hiyelbaz** [comment]
+1 for remix.js support. Struggled with the same problem same problem. Afaik, manually modifying package.json files is the only workaround for now.
