### ISSUE TITLE
Example code does not work - Some svelte conflict?

### ISSUE THREAD

**Issue by dikovmaxim** [konstaui/konsta#86]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://konstaui.com/svelte/usage

### Bug description

Hi. I just created a basic svelte application with the following App.svelte code:
```
<script>
	/* App.svelte */
	import { Block, Button } from 'konsta/svelte';
  </script>

  <Block class="space-y-4">
	<p>Here comes the button</p>
	<Button>Action</Button>
  </Block>
```

I Installed tailwind css and followerd all Instructions, but my application won't buid
```
────────────────── LOGS ──────────────────

publicFolder is public
rollup v1.16.3
bundles src/main.js → public\bundle.js...
[!] (plugin svelte) ParseError: Valid <svelte:...> tag names are svelte:head, svelte:options, svelte:window, svelte:body, svelte:self or svelte:component
node_modules\konsta\svelte\components\ActionsButton.svelte
71: </script>
72:
73: <svelte:element
     ^
74:   this={Component}
75:   bind:this={rippleEl.current}
ParseError: Valid <svelte:...> tag names are svelte:head, svelte:options, svelte:window, svelte:body, svelte:self or svelte:component
    at error$1 (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$2.error (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\parse\index.ts:93:3)
    at read_tag_name (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\parse\state\tag.ts:303:10)
    at tag (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\parse\state\tag.ts:101:15)
    at new Parser$2 (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\parse\index.ts:45:12)
    at parse$2 (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\parse\index.ts:208:17)
    at parse (C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\svelte\src\compiler\compile\index.ts:68:14)
    at C:\Users\max\Desktop\MyApp\MyApp\MyApp\node_modules\rollup-plugin-svelte\index.js:252:22
```

### Expected Behavior

Should display a basic app

### Actual Behavior

Throws an error

### Konsta UI version

1.0.2 (just installed it from npm)

### Platform/Target and Browser Versions

Firefox

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dikovmaxim** [comment]
```
<script>
	/* App.svelte */
	import { Block, Button } from 'konsta/svelte';
  </script>

```
After reading a log I provided, it really looks like it is a framework-specific problem, but aven this code in enough yo produce the same error

**Comment by nolimits4web** [comment]
Make sure you are using latest Svelte version

**Comment by dikovmaxim** [comment]
I just updated

> 

I just updated

**Comment by dikovmaxim** [comment]
I just updated
