### ISSUE TITLE
Nuxt 3 Starter template is unstyled

### ISSUE THREAD

**Issue by MarvinMuuss** [konstaui/konsta#93]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://stackblitz.com/edit/nuxt-starter-dpsggb

### Bug description

Hey there,
first I had troubles compiling the Nuxt 3 starter, I think the referenced Stackblitz is a little bit out of date. 
So I've created a new one, but here the starter is unstyled. 

### Expected Behavior

That the starter works as described in the docs.

### Actual Behavior

With Konsta 0.11.0 like in the [Nuxt 3 Starter Stackblitz](https://stackblitz.com/edit/github-whecpx?file=nuxt.config.ts) ([GitHub Repo](https://github.com/konstaui/konsta-nuxt3-starter)) the server starts with
```
 ERROR  Cannot start nuxt:  nuxt.options.serverMiddleware is not iterable                            

  at resolveHandlers (node_modules/nuxt/dist/index.mjs:1257:30)
  at initNitro (node_modules/nuxt/dist/index.mjs:1121:43)
  at initNuxt (node_modules/nuxt/dist/index.mjs:1357:9)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6793:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6854:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:65:20)
```

Updating Konsta to v1.0.2 and Nuxt to 3.0.0-rc.13 compiles the code but the UI is unstyled.

### Konsta UI version

1.0.2

### Platform/Target and Browser Versions

macOS Monterey 12.4, Chrome Version 107.0.5304.87 (Official Build) (arm64), Firefox 106.0.5 (64-Bit

### Validations

- [X] Follow our [Code of Conduct](https://github.com/konstaui/konsta/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://konstaui.com).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Konsta UI issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by MarvinMuuss** [comment]
Mea culpa, it was my fault.
I did not properly copy the `export default` in the `index.vue`. 
A copy function for the code sections would be great 😄 

Sorry for the fuzz, have a great day!
